spring:
  #静态资源处理
  resources:
    #启动默认静态资源处理，默认启动
    add-mappings: true
    cache:
      cachecontrol:
        #缓存响应时间，单位秒
        max-age: 3600
    chain:
      #资源配链启动缓存，默认启动
      cache: true
      #启动资源链，默认禁用
      enabled: true
      #启用压缩资源（gzip，brotil）解析，默认禁用
      compressed: true
      #启用h5应用缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/static/
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miao_sha?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #    username: user
    #    password: zgt9321@qq.com
    username: root
    password: 123456
    # springboot自带的数据库连接池
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 3000
      connection-test-query: SELECT 1
  redis:
    timeout: 10000ms
    host: 106.14.219.106
    password: zgt9321@qq.com
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: 2000ms
        max-idle: 200
  rabbitmq:
    host: 106.14.219.106
    username: root
    password: root
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完在继续下一条消息
        prefetch: 1
        #启动是默认启动容器
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数，默认3次
        max-attempts: 3
        #最大重试间隔时间
        max-interval: 10000ms
        #重试的间隔乘数，比如配2。0  第一等10s 第二次等20s 第三次等40s
        multiplier: 1

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.jiao.entity
logging:
  level:
    com.jiao.mapper: debug
